=== ralfeus/ActivityEvidence/settings.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="SaveAction" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Clear" />
      <xs:enumeration value="Clone" />
      <xs:enumeration value="Close" />
      <xs:enumeration value="StartWorking" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="URL" type="xs:string" />
        <xs:element name="CommunicationURL" type="xs:string" />
        <xs:element name="AdminID" type="xs:string" />
        <xs:element name="ReminderTimer" type="xs:unsignedByte" />
        <xs:element name="DefaultSaveAction" type="SaveAction" />
        <xs:element name="DefaultCustomer" type="xs:string" />
        <xs:element name="DefaultActivity" type="xs:string" />
        <xs:element maxOccurs="unbounded" name="CustomerDefaultActivity">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="Customer" type="xs:string" use="required" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ralfeus/ActivityEvidence/bin/Release/settings.xml
<?xml version="1.0" encoding="windows-1251" standalone="yes"?>
<settings
  xmlns="http://activity.evidence.cz.ibm.com/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://activity.evidence.cz.ibm.com/ settings.xsd">
  <URL>http://9.158.161.135/activities_evidence/service.new.php</URL>
  <CommunicationURL>http://9.158.161.135/activities_evidence/communication_service.new.php</CommunicationURL>
  <AdminID>Z61386</AdminID>
  <ReminderTimer>1</ReminderTimer>
  <DefaultSaveAction>StartWorking</DefaultSaveAction>
  <DefaultCustomer>Sued-Chemie</DefaultCustomer>
  <DefaultActivity>Troubleshooting</DefaultActivity>
  <CustomerDefaultActivity Customer="VIG">Backup check</CustomerDefaultActivity>
  <CustomerDefaultActivity Customer="Automobile Associate (AA)">Hypersoft (troubleshooting)</CustomerDefaultActivity>
  <CustomerDefaultActivity Customer="Carlsberg">Troubleshooting</CustomerDefaultActivity>
  <CustomerDefaultActivity Customer="ABB">Hypersoft (administration)</CustomerDefaultActivity>
  <Update>False</Update>
</settings>
